services:
  event-db:
    image: postgres:16
    container_name: event-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    volumes:
      - event-db:/var/lib/postgresql/data
    networks:
      - event-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "5433:5433"
  
volumes:
  event-db:

networks:
  event-net: